// <copyright file="Strings.cs">
// Copyright (c) AeroTerm Developers. All rights reserved.
// Licensed under the GPLv2 license. See LICENSE file in the project root for full license information.
// </copyright>

namespace AeroTerm.Resources;

using System.Globalization;
using System.Resources;
using AeroTerm.Services;

/// <summary>
/// Strongly-typed, hand-written accessor for the <c>Strings.resx</c>
/// resource bundle. Hand-written (rather than generated by
/// <c>ResXFileCodeGenerator</c>) so the SDK-style csproj stays free of
/// Visual-Studio-specific code-gen tooling while still exposing
/// ergonomic, compile-checked keys such as
/// <c>{x:Static strings:Strings.SettingsTitle}</c> from AXAML.
/// <para>
/// Lookups go through <see cref="LocalizationHost"/>, which honours
/// <see cref="CultureInfo.CurrentUICulture"/> and falls back to the
/// English baseline when a key is missing in a satellite assembly.
/// </para>
/// </summary>
public static class Strings
{
    /// <summary>
    /// The <see cref="ResourceManager"/> backing every property on this
    /// class. Exposed so tests and <see cref="LocalizationHost"/> can
    /// drive lookups through the same instance the UI uses.
    /// </summary>
    public static readonly ResourceManager ResourceManager = new(
        "AeroTerm.Resources.Strings",
        typeof(Strings).Assembly);

    /// <summary>Gets the application window title (e.g. <c>AeroTerm</c>).</summary>
    public static string AppTitle => Get(nameof(AppTitle));

    /// <summary>Gets the Settings window title.</summary>
    public static string SettingsTitle => Get(nameof(SettingsTitle));

    /// <summary>Gets the command-palette window title.</summary>
    public static string CommandPaletteTitle => Get(nameof(CommandPaletteTitle));

    /// <summary>Gets the confirm-close dialog title.</summary>
    public static string ConfirmCloseTitle => Get(nameof(ConfirmCloseTitle));

    /// <summary>Gets the font-picker dialog title.</summary>
    public static string FontPickerTitle => Get(nameof(FontPickerTitle));

    /// <summary>Gets the generic "OK" button caption.</summary>
    public static string ButtonOk => Get(nameof(ButtonOk));

    /// <summary>Gets the generic "Cancel" button caption.</summary>
    public static string ButtonCancel => Get(nameof(ButtonCancel));

    /// <summary>Gets the generic "Close" button caption.</summary>
    public static string ButtonClose => Get(nameof(ButtonClose));

    /// <summary>Gets the "Add..." button caption used by list editors.</summary>
    public static string ButtonAdd => Get(nameof(ButtonAdd));

    /// <summary>Gets the "Remove" button caption used by list editors.</summary>
    public static string ButtonRemove => Get(nameof(ButtonRemove));

    /// <summary>Gets the "Move Up" button caption used by list editors.</summary>
    public static string ButtonMoveUp => Get(nameof(ButtonMoveUp));

    /// <summary>Gets the "Move Down" button caption used by list editors.</summary>
    public static string ButtonMoveDown => Get(nameof(ButtonMoveDown));

    /// <summary>Gets the AppearancePage "Window" group header.</summary>
    public static string AppearanceWindowHeader => Get(nameof(AppearanceWindowHeader));

    /// <summary>Gets the AppearancePage "Font" group header.</summary>
    public static string AppearanceFontHeader => Get(nameof(AppearanceFontHeader));

    /// <summary>Gets the AppearancePage "Color Scheme" group header.</summary>
    public static string AppearanceColorSchemeHeader => Get(nameof(AppearanceColorSchemeHeader));

    /// <summary>Gets the AppearancePage "Bell" group header.</summary>
    public static string AppearanceBellHeader => Get(nameof(AppearanceBellHeader));

    /// <summary>Gets the AppearancePage "Scrollback" group header.</summary>
    public static string AppearanceScrollbackHeader => Get(nameof(AppearanceScrollbackHeader));

    /// <summary>Gets the AppearancePage "Tab Bar" group header.</summary>
    public static string AppearanceTabBarHeader => Get(nameof(AppearanceTabBarHeader));

    /// <summary>Gets the AppearancePage "General" group header.</summary>
    public static string AppearanceGeneralHeader => Get(nameof(AppearanceGeneralHeader));

    /// <summary>Gets the AppearancePage window-transparency check-box caption.</summary>
    public static string AppearanceEnableTransparency => Get(nameof(AppearanceEnableTransparency));

    /// <summary>Gets the AppearancePage ligature check-box caption.</summary>
    public static string AppearanceEnableLigature => Get(nameof(AppearanceEnableLigature));

    /// <summary>Gets the AppearancePage "Confirm on close" check-box caption.</summary>
    public static string AppearanceConfirmOnClose => Get(nameof(AppearanceConfirmOnClose));

    /// <summary>Gets the palette caption for "New Tab".</summary>
    public static string PaletteNewTab => Get(nameof(PaletteNewTab));

    /// <summary>Gets the palette caption for "Close Tab".</summary>
    public static string PaletteCloseTab => Get(nameof(PaletteCloseTab));

    /// <summary>Gets the palette caption for "Open Settings".</summary>
    public static string PaletteOpenSettings => Get(nameof(PaletteOpenSettings));

    /// <summary>
    /// Gets the <see cref="string.Format(IFormatProvider, string, object?)"/> template for
    /// the confirm-close dialog body (e.g. <c>{0} tabs are open. Close them all?</c>).
    /// Callers are expected to format with the tab count.
    /// </summary>
    public static string ConfirmCloseMessageFormat => Get(nameof(ConfirmCloseMessageFormat));

    private static string Get(string key) => LocalizationHost.GetString(key);
}
